name: Update Configs

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install requests beautifulsoup4

      - name: Run Script
        run: python main.py

      - name: Remove old configs5 (deprecated)
        run: rm -f configs5.txt

      - name: Commit and Push
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add 1.txt 2.txt 3.txt 4.txt data.temp pointer.txt inactive_channels.txt || git add .
          git commit -m "Update configs and inactive channels list" || exit 0
          git push
